### ISSUE TITLE
This works only for associated view

### ISSUE THREAD

**Issue by xrmprofessional** [PaulNieuwelaar/filteraddexisting#1]
Not working from subgrid on the main form, if I change the command of the add existing button the + button disappear from subgrid
It works only when you go to the associated view

**Comment by PaulNieuwelaar** [comment]
Did you change the id of the button? For subgrids CRM only displays the buttons if they have the same id as the ootb button. Also did you make sure you updated the command for the right add existing button? Which CRM version is this?

**Comment by xrmprofessional** [comment]
I found out that the Id of the command must also be the same as the OOTB command then it works, thanks
