### ISSUE TITLE
Unified Interface

### ISSUE THREAD

**Issue by thomassandsor** [PaulNieuwelaar/filteraddexisting#2]
Any idea if this is possible to do in the new UI at any point?

**Comment by PaulNieuwelaar** [comment]
This is now possible in the unified interface using the ```filters``` on [lookupOptions](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/xrm-utility/lookupobjects#parameters). I've updated the [example code](https://github.com/PaulNieuwelaar/filteraddexisting/blob/master/source_v9.js) to use this.
